

spring.data.mongodb.uri=mongodb+srv://ritwiksaxena19_db_user:ritwik123@cluster0.3acl9c1.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true